config/routes.rb
Rails.application.routes.draw do



  #resources :users

  root 'static_pages#index'

  get 'about' => 'about#index'

  resources :messages, only: [:new, :create]


  resources :posts, only: [:index, :show]

  # Admin Routes / Scoping
  scope :admin, admin_scope: true do 

    # This allows us to have /admin as a default index action
    # And then have all the items within it under the same path
    # We also use some cleverness of scope/namespace where we can set our own parameters

    get "/" => "admin#index", as: "admin_root", format: false

    get    '/users'         => 'users#index',   as: :admin_users
    get    '/user/new'      => 'users#new',     as: :admin_user_new
    post   '/user'          => 'users#create',  as: :admin_user_create
    get    '/user/:id'      => 'users#show',    as: :admin_user_show
    get    '/user/:id/edit' => 'users#edit',    as: :admin_user_edit
    patch  '/user/:id'      => 'users#update',  as: :admin_user_update
    delete '/user/:id'      => 'users#destroy', as: :admin_user_destroy


      get    'login'  => 'sessions#new'
      post   'login'  => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      get '/posts' => 'admin#posts', as: :admin_posts
      # Messages
      get '/messages' => 'admin#messages', as: :admin_messages
      get '/message/:id' => 'admin#show_message', as: :admin_message
      delete '/message/:id' => 'admin#delete_message', as: :admin_delete_message

      get    '/post/new'       => 'posts#new',     as: :admin_post_new
      post   '/post'           => 'posts#create',  as: :admin_post_create
      get    '/post/:id'       => 'posts#show_admin',    as: :admin_post_show
      get    '/post/:id/edit'  => 'posts#edit',    as: :admin_post_edit
      patch  '/post/:id'       => 'posts#update',  as: :admin_post_update

  end

end

app/views/admin/_index_content.html.erb
<h1>Index</h1> 

app/views/admin/index.html.erb
<%= render 'index_content' %>	

app/views/admin/messages.html.erb
<br><br>

<% if @messages.count > 0 %>

	<div class="table-responsive">
		<table class="table table-bordered table-hover">
		  <thead>
		  	<tr>
		  		<th>Name</th>
		  		<th>Message</th>
		  		<th>Email</th>
		  		<th></th>
		  	</tr>
		  </thead>
		  <tbody>
			  <% @messages.each do |message| %>

			  	<% color = message.read ? '' : 'red' %>

			  	<tr class="active" onclick="document.location='<%= admin_message_path(message) %>';" style="cursor:pointer;">
			  		<td style="color: <%= color %>"><%= message.name %></td>
			  		<td><%= message.message.truncate(30) %></td>
			  		<td><%= message.email %></td>
			  		<td><%= link_to 'Delete', admin_delete_message_path(message), method: :delete, class: 'btn btn-xs btn-danger' %></td>
			  	</tr>

			  <% end %>
			</tbody>
		</table>
	</div>
<% else %>

	<h3>No Messages</h3>

<% end %>

app/views/admin/posts.html.erb
<br><br>

<%= link_to 'New Post', admin_post_new_path, class:'btn btn-primary' %>
<br><br>

<div class="table-responsive">
	<table class="table table-bordered table-hover">
	  <thead>
	  	<tr>
	  		<th>Title</th>
	  		<th>Content</th>
	  		<th>Archived</th>
	  	</tr>
	  </thead>
	  <tbody>
		  <% @posts.each do |post| %>

		  	<tr class="active" onclick="document.location='<%= admin_post_show_path(post) %>';" style="cursor:pointer">
		  		<td><%= post.title %></td>
		  		<td><%= post.content.truncate(30) %></td>
		  		<td><%= post.archived %></td>
		  	</tr>

		  <% end %>
		</tbody>
	</table>
</div>

app/views/admin/show_message.html.erb
 <div class="col-xs-8  main_content blog_content" >
	
	<%= link_to 'Back', admin_messages_path, class: 'btn btn-primary btn-xs' %>
	<%= link_to 'Delete', admin_delete_message_path(@message), method: :delete, class: 'btn btn-danger btn-xs' %>

	<h2 class="page-header"><%= @message.name %></h2>
	<h2 class="page-header"><%= @message.email %></h2>

	<content class="content"><%= markdown(@message.message) %></content>
		                   
</div>

<%= render 'layouts/admin_side_bar' %>	