config/routes.rb
Rails.application.routes.draw do



  #resources :users

  root 'static_pages#index'

  get 'about' => 'about#index'

  resources :messages, only: [:new, :create]


  resources :posts, only: [:index, :show]

  # Admin Routes / Scoping
  scope :admin, admin_scope: true do 

    # This allows us to have /admin as a default index action
    # And then have all the items within it under the same path
    # We also use some cleverness of scope/namespace where we can set our own parameters

    get "/" => "admin#index", as: "admin_root", format: false

    get    '/users'         => 'users#index',   as: :admin_users
    get    '/user/new'      => 'users#new',     as: :admin_user_new
    post   '/user'          => 'users#create',  as: :admin_user_create
    get    '/user/:id'      => 'users#show',    as: :admin_user_show
    get    '/user/:id/edit' => 'users#edit',    as: :admin_user_edit
    patch  '/user/:id'      => 'users#update',  as: :admin_user_update
    delete '/user/:id'      => 'users#destroy', as: :admin_user_destroy


      get    'login'  => 'sessions#new'
      post   'login'  => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      get '/posts' => 'admin#posts', as: :admin_posts
      # Messages
      get '/messages' => 'admin#messages', as: :admin_messages
      get '/message/:id' => 'admin#show_message', as: :admin_message
      delete '/message/:id' => 'admin#delete_message', as: :admin_delete_message

      get    '/post/new'       => 'posts#new',     as: :admin_post_new
      post   '/post'           => 'posts#create',  as: :admin_post_create
      get    '/post/:id'       => 'posts#show_admin',    as: :admin_post_show
      get    '/post/:id/edit'  => 'posts#edit',    as: :admin_post_edit
      patch  '/post/:id'       => 'posts#update',  as: :admin_post_update

  end

end

app/models/user.rb
class User < ActiveRecord::Base
	
	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { in: 1..50 }
	validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
	

	has_secure_password
	#has_many :posts

	attr_accessor :remember_token

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns a hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																								 BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Returns true if the given token matches the digest
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(:remember_token)
	end

	# Forgets a user
	def forget
		update_attribute(:remember_token, nil)
	end

	def self.edit_correct_user_data(user, model)
		if model.constantize.where(user_id: user.id).present?
			return true
		else
			return false
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy]
#  before_action :correct_user, only: [:edit, :update, :show]
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :admin_user

  #after_filter :verify_authorized, only: [ :index] 

  def index
    @users = User.all
   # authorize @users
  end

   def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to admin_users_path, notice: "User Created" 
    else
      redirect_to admin_user_new_path
      flash[:error] = AlertsHelper.getErrorAlertMessages(@user)
    
    end
  end

  def edit
    @user
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_users_path, notice: "Profile Updated" 
    else
    redirect_to admin_user_edit_path(@user)
    flash[:error] = AlertsHelper.getErrorAlertMessages(@user)
    end
  end

  def destroy
    @user.destroy
    #authorize @user
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end

  def show
    @user
    #authorize @user
  end

  private

    # Before Filters

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_path
      end
    end

    # Confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        flash[:error] = "You are not allowed to perform this action"
        redirect_to root_path 
      end
    end

    # Sets the current user for edit show update destroy
    def set_user
      @user = User.find(params[:id])
    end

    # Confirms an admin user
    def admin_user
      if current_user.nil? || !current_user.admin? 
        redirect_to root_path
        flash[:error] = "You are not allowed to perform that action"
      end 
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user, url: @user.new_record? ? admin_user_create_path : admin_user_update_path do |f| %>
	<div class="col-md-6 col-offset-3">
		
		<div class="from-group">
			<%= f.label :name %>
			<%= f.input_field :name, label: false, class:'form-control' %>
		</div>

		<div class="from-group">
			<%= f.label :email %>
			<%= f.email_field :email, label: false, class:'form-control' %>
		</div>


		<div class="from-group">
			<%= f.label :password %>	
			<%= f.password_field :password, label: false, class:'form-control' %>
		</div>

		<div class="from-group">
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, label: false, class:'form-control'  %>
		</div>

		<div >
			<%= f.input :admin, as: :boolean %>
		</div>

		<br>
		<%= f.submit @user.new_record? ? "Create User" : "Update User" , class:'btn btn-primary' %>

	</div>
<% end %>

app/views/users/_index_content.html.erb
<br><br>

<%= link_to 'New User', admin_user_new_path, class:'btn btn-primary' %>
<br><br>

<div class="table-responsive">
	<table class="table table-bordered table-hover">
	  <thead>
	  	<tr>
	  		<th>Name</th>
	  		<th>Email</th>
	  		<th>Admin</th>
	  	</tr>
	  </thead>
	  <tbody>
		  <% @users.each do |user| %>

		  	<tr class="active" onclick="document.location='<%= admin_user_edit_path(user) %>';">
		  		<td><%= user.name %></td>
		  		<td><%= user.email %></td>
		  		<td><%= user.admin %>
		  			<% unless current_user == user %>
		  				<%= link_to 'Delete', admin_user_destroy_path(user), method: :delete, class: 'btn btn-danger btn-xs pull-right' %>
		  			<% end %>
		  		</td>
		  	</tr>

		  <% end %>
		</tbody>
	</table>
</div>

app/views/users/edit.html.erb
<%= render "form" %> 

app/views/users/index.html.erb
<%= render 'index_content' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile</h1>

<h2>Name is <%= @user.name %></h2>
<h2>Email is <%= @user.email %></h2>