config/routes.rb
Rails.application.routes.draw do



  #resources :users

  root 'static_pages#index'

  get 'about' => 'about#index'

  resources :messages, only: [:new, :create]


  resources :posts, only: [:index, :show]

  # Admin Routes / Scoping
  scope :admin, admin_scope: true do 

    # This allows us to have /admin as a default index action
    # And then have all the items within it under the same path
    # We also use some cleverness of scope/namespace where we can set our own parameters

    get "/" => "admin#index", as: "admin_root", format: false

    get    '/users'         => 'users#index',   as: :admin_users
    get    '/user/new'      => 'users#new',     as: :admin_user_new
    post   '/user'          => 'users#create',  as: :admin_user_create
    get    '/user/:id'      => 'users#show',    as: :admin_user_show
    get    '/user/:id/edit' => 'users#edit',    as: :admin_user_edit
    patch  '/user/:id'      => 'users#update',  as: :admin_user_update
    delete '/user/:id'      => 'users#destroy', as: :admin_user_destroy


      get    'login'  => 'sessions#new'
      post   'login'  => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      get '/posts' => 'admin#posts', as: :admin_posts
      # Messages
      get '/messages' => 'admin#messages', as: :admin_messages
      get '/message/:id' => 'admin#show_message', as: :admin_message
      delete '/message/:id' => 'admin#delete_message', as: :admin_delete_message

      get    '/post/new'       => 'posts#new',     as: :admin_post_new
      post   '/post'           => 'posts#create',  as: :admin_post_create
      get    '/post/:id'       => 'posts#show_admin',    as: :admin_post_show
      get    '/post/:id/edit'  => 'posts#edit',    as: :admin_post_edit
      patch  '/post/:id'       => 'posts#update',  as: :admin_post_update

  end

end

app/models/post.rb
class Post < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :user

	validates :title, presence: true, length: {in: 2..50}
	validates :content, presence: true, length: {in: 2..9999999999999}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, except: [ :new, :index, :create ] 
	before_action :require_admin, except: [ :index, :show ]

	def index
		@posts = Post.all.where(archived: false)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "Post Created"
			redirect_to admin_post_show_path(@post)
		else
			flash[:error] = AlertsHelper.getErrorAlertMessages(@post)
			redirect_to admin_post_new_path
		end
	end

	def show
		render layout: 'application'
	end

	def show_admin
		@post
	end

	def edit
		@post
	end

	def update
		if @post.update_attributes(post_params)
			flash[:notice] = "Post Updated"
			redirect_to admin_post_show_path(@post)
		else
			flash[:error] = AlertsHelper.getErrorAlertMessages(@post)
			redirect_to admin_post_edit_path(@post)
		end
	end

	private

		def post_params
			params.require(:post).permit(:user_id, :content, :title, :archived, :slug)
		end

		# Before filters

		def set_post
			@post = Post.friendly.find(params[:id])
		end

		def require_admin
			if params[:admin_scope].present? && params[:admin_scope] == true
				return true
			else
				redirect_to root_path
				flash[:warning] = "You are not allowed to perform that action"
				return false
			end
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

	// CONFIG VARIABLES 
	var disqus_shortname = 'scorpionking';
	var disqus_identifier = '<%= @post.id %>';
	var disqus_title = '<%= @post.title %>';
	var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';


	/*var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	}; */


	(function() { // DON'T EDIT BELOW THIS LINE
		var d = document, s = d.createElement('script');
		s.src = '//scorpionking.disqus.com/embed.js';
		s.setAttribute('data-timestamp', +new Date());
		(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                                

app/views/posts/_form.html.erb
<br><br><br><br>

<%= simple_form_for @post, url: @post.new_record? ? admin_post_create_path : admin_post_update_path do |f| %>
	<div class="row">
		<div class="col-md-12">
			
			<div class="from-group ">
				<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id },  label: false, class:'form-control' %>
			</div>		

			<div class="from-group">
				<%= f.label :title %>
				<%= f.input :title, label: false, class:'form-control' %>
			</div>

			<div class="from-group">
				<%= f.label :content %>
				<%= f.input :content, as: :text, label: false, input_html: { class: 'form-control', rows: 33, cols:180 } %>
			</div>

			<div class="form-group">
				
				<%= f.input :archived, as: :boolean %>
			</div>

			<br>
			<%= f.submit @post.new_record? ?  'Create Post' : 'Update Post', class:'btn btn-primary' %>
			<% unless @post.new_record? %>
				<%= link_to 'Back', admin_post_show_path(@post), class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/posts/_index_content.html.erb
<%= render 'layouts/page_header', locals: { image_path: 'post.jpg' } %>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
               
            </div>
        </div>
    </div>
</article>

<hr>

app/views/posts/_show_shared.html.erb
<% 
	admin_login = true if !current_user.nil? && current_user.admin? 
%>

 <div class="col-xs-8  main_content blog_content" >
	<% if admin_login %>
		<%= link_to 'Back', admin_posts_path, class: 'btn btn-primary btn-xs' %>
		<%= link_to 'Edit', admin_post_edit_path(@post), class:'btn btn-primary btn-xs' %>
	<% end %>

	<h1 class="page-header"><%= @post.title %></h1>

	<content class="content"><%= markdown(@post.content) %></content>

	<!--<h2>Posted by <%# @post.user.name %></h2> -->
	






		
	<div id="share_box">

		<!-- Twitter -->
		<a title="Share on Twitter" class="pointer" onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @cata94v - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i style="font-size: 22px" class="fa fa-2x fa-twitter glyphics white_with_black_border" aria-hidden="true"></i></a>
		<!-- Facebook -->
		<a title="Share on Facebook" class="pointer" onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i style="font-size: 22px" class="fa fa-2x fa-facebook white_with_black_border" aria-hidden="true"></i></a>
		<!-- Google Plus -->
		<a title="Share on Google Plus" class="pointer" style="margin-left: 7px" onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i style="font-size: 22px" class="fa fa-2x fa-google-plus white_with_black_border" aria-hidden="true"></i></a>
	</div>

	<%= render 'disqus' %>                   

</div>

<%= render 'shared/side_bar' %>	

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
 <div class="col-xs-8  main_content blog_content" >
	<% if params[:admin_scope] == true && current_user.admin == true %>
		<%= link_to 'Back', admin_posts_path, class: 'btn btn-primary btn-xs' %>
		<%= link_to 'Edit', admin_post_edit_path(@post), class:'btn btn-primary btn-xs' %>
	<% end %>

	<h1 class="page-header"><%= @post.title %></h1>

	<content class="content"><%= markdown(@post.content) %></content>

	<!--<h2>Posted by <%# @post.user.name %></h2> -->




	<% unless params[:admin_scope] %>
		<div id="share_box">
			<p>Share this article or Post Title?</p>
			<!-- Twitter -->
			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @cata94v - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">Twitter</a>
			<!-- Facebook -->
			<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">Facebook</a>
			<!-- Google Plus -->
			<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">Google Plus</a>
		</div>

		<%= render 'disqus' %>                   
	<% end %>

</div>

<%= render 'shared/side_bar' %>	

app/views/posts/show_admin.html.erb
<%= render 'show_shared' %>