config/routes.rb
Rails.application.routes.draw do



  #resources :users

  root 'static_pages#index'

  get 'about' => 'about#index'

  resources :messages, only: [:new, :create]


  resources :posts, only: [:index, :show]

  # Admin Routes / Scoping
  scope :admin, admin_scope: true do 

    # This allows us to have /admin as a default index action
    # And then have all the items within it under the same path
    # We also use some cleverness of scope/namespace where we can set our own parameters

    get "/" => "admin#index", as: "admin_root", format: false

    get    '/users'         => 'users#index',   as: :admin_users
    get    '/user/new'      => 'users#new',     as: :admin_user_new
    post   '/user'          => 'users#create',  as: :admin_user_create
    get    '/user/:id'      => 'users#show',    as: :admin_user_show
    get    '/user/:id/edit' => 'users#edit',    as: :admin_user_edit
    patch  '/user/:id'      => 'users#update',  as: :admin_user_update
    delete '/user/:id'      => 'users#destroy', as: :admin_user_destroy


      get    'login'  => 'sessions#new'
      post   'login'  => 'sessions#create'
      delete 'logout' => 'sessions#destroy'

      get '/posts' => 'admin#posts', as: :admin_posts
      # Messages
      get '/messages' => 'admin#messages', as: :admin_messages
      get '/message/:id' => 'admin#show_message', as: :admin_message
      delete '/message/:id' => 'admin#delete_message', as: :admin_delete_message

      get    '/post/new'       => 'posts#new',     as: :admin_post_new
      post   '/post'           => 'posts#create',  as: :admin_post_create
      get    '/post/:id'       => 'posts#show_admin',    as: :admin_post_show
      get    '/post/:id/edit'  => 'posts#edit',    as: :admin_post_edit
      patch  '/post/:id'       => 'posts#update',  as: :admin_post_update

  end

end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
 <!--      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
   <!--    <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_admin_side_bar.html.erb
  <div id="wrapper">

        <!-- Sidebar -->
      <% if current_user && current_user.admin %>
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <%= link_to "Dashboard", admin_root_path %>
                </li>
                <li>
                    <%= link_to "Posts", admin_posts_path %>
                </li>
                <li>
                    <%= link_to "Messages", admin_messages_path %>
                </li>
                <li>
                    <%= link_to 'Users', admin_users_path %>
                </li>
                <li>
                    <%= link_to "Log Out", logout_path, method: :delete %>
                </li>
            </ul>
        </div>
      <% end %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">

                         <%= render 'layouts/flash_messages' %>
                        
                         <%= yield %>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

app/views/layouts/_flash_messages.html.erb
<% donotdismiss = "" %>
<% containerID = "flashContainer" %>
<% flash.each do |name, msg| %>
  <% 

    donotdismiss = "no-dismiss" if name.to_s =~ /_exception$/
    containerID = "flashContainerNoDismiss" if name.to_s =~ /_exception$/

    name = name.gsub("_exception", "")
    if name == 'notice'
      alert_class = 'alert-success'
    elsif name == 'error'
      alert_class = 'alert-danger'
    else
      alert_class = 'alert-warning'
    end
%>
  <div id="<%=containerID%>" class="alert <%= alert_class %>" role="alert" <%= donotdismiss %>>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div id="flashMessage">
      <%= msg.html_safe %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <%= render partial: 'layouts/google_analytics' %>

</footer>

<!-- <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91664959-1', 'https://dry-lowlands-51598.herokuapp.com/');
  ga('send', 'pageview');

</script> -->

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-91664959-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
	<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header page-scroll">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							Menu <i class="fa fa-bars"></i>
					</button>
						<%= link_to "Start Bootstrap", root_path, class:'navbar-brand' %>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
							<li>
								<%= link_to "Home", root_path %>
							</li>
							<li>
								<%= link_to "About", about_path %>
							</li>
							<li>
								<%= link_to "Posts", posts_path %>								
							</li>
							<li>
								<%= link_to "Contact", new_contact_path %>
							</li>
							<% if logged_in? %>
								<li><%= link_to 'Log out', logout_path, method: :delete %></li>
							<% else %>
								<li><%= link_to "Sign up", login_path %></li>
							<% end %>
					</ul>
			</div>
	</div>
</nav>

app/views/layouts/_page_header.html.erb
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top blog_navbar" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar_content" align="center">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Start Bootstrap</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Services</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  


</head>
<body>

  <% if current_user.present? && current_user.admin %>
	  <%= render 'layouts/admin_header' %>
  <% end %>

	<%= render 'layouts/admin_side_bar' %>


  


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'blog/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'blog/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
    
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">


</head>
<body>
 
  <%# render 'layouts/page_header' %>

  <div class="container">
    <div class="row">
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
    </div>
  </div>

	<%= render 'layouts/footer' %>

</body>
</html>